INSERT INTO category VALUES (1, "Horreur");


INSERT INTO program (id, title, summary, poster, category_id) VALUES 

(NULL, "Walking Dead", "Le policier Rick Grimes se réveille après un long coma. Il découvre avec effarement que le monde, ravagé par une épidémie, est envahi par les morts-vivants.", "https://m.media-amazon.com/images/M/MV5BZmFlMTA0MmUtNWVmOC00ZmE1LWFmMDYtZTJhYjJhNGVjYTU5XkEyXkFqcGdeQXVyMTAzMDM4MjM0._V1_.jpg", 1), 

(NULL, "The Haunting Of Hill House", "Plusieurs frères et sœurs qui, enfants, ont grandi dans la demeure qui allait devenir la maison hantée la plus célèbre des États-Unis, sont contraints de se réunir pour finalement affronter les fantômes de leur passé.", "https://m.media-amazon.com/images/M/MV5BMTU4NzA4MDEwNF5BMl5BanBnXkFtZTgwMTQxODYzNjM@._V1_SY1000_CR0,0,674,1000_AL_.jpg", 1), 

(NULL, "American Horror Story", "A chaque saison, son histoire. American Horror Story nous embarque dans des récits à la fois poignants et cauchemardesques, mêlant la peur, le gore et le politiquement correct.", "https://m.media-amazon.com/images/M/MV5BODZlYzc2ODYtYmQyZS00ZTM4LTk4ZDQtMTMyZDdhMDgzZTU0XkEyXkFqcGdeQXVyMzQ2MDI5NjU@._V1_SY1000_CR0,0,666,1000_AL_.jpg", 1), 

(NULL, "Love Death And Robots", "Un yaourt susceptible, des soldats lycanthropes, des robots déchaînés, des monstres-poubelles, des chasseurs de primes cyborgs, des araignées extraterrestres et des démons assoiffés de sang : tout ce beau monde est réuni dans 18 courts métrages animés déconseillés aux âmes sensibles.", "https://m.media-amazon.com/images/M/MV5BMTc1MjIyNDI3Nl5BMl5BanBnXkFtZTgwMjQ1OTI0NzM@._V1_SY1000_CR0,0,674,1000_AL_.jpg", 1), 

(NULL, "Penny Dreadful", "Dans le Londres ancien, Vanessa Ives, une jeune femme puissante aux pouvoirs hypnotiques, allie ses forces à celles d Ethan, un garçon rebelle et violent aux allures de cowboy, et de Sir Malcolm, un vieil homme riche aux ressources inépuisables.  Ensemble, ils combattent un ennemi inconnu, presque invisible, qui ne semble pas humain et qui massacre la population.", "https://m.media-amazon.com/images/M/MV5BNmE5MDE0ZmMtY2I5Mi00Y2RjLWJlYjMtODkxODQ5OWY1ODdkXkEyXkFqcGdeQXVyNjU2NjA5NjM@._V1_SY1000_CR0,0,695,1000_AL_.jpg", 1), 

(NULL, "Fear The Walking Dead", "La série se déroule au tout début de l épidémie relatée dans la série-mère The Walking Dead et se passe dans la ville de Los Angeles, et non à Atlanta. Madison est conseillère dans un lycée de Los Angeles. Depuis la mort de son mari, elle élève seule ses deux enfants : Alicia, excellente élève qui découvre les premiers émois amoureux, et son grand frère Nick qui a quitté la fac et a sombré dans la drogue.", "https://m.media-amazon.com/images/M/MV5BYWNmY2Y1NTgtYTExMS00NGUxLWIxYWQtMjU4MjNkZjZlZjQ3XkEyXkFqcGdeQXVyMzQ2MDI5NjU@._V1_SY1000_CR0,0,666,1000_AL_.jpg", 1);


INSERT INTO program (id, title, summary, poster, category_id) VALUES 

(NULL, "La ligne verte", "Paul Edgecomb, Gardien-chef du pénitencier de Cold Mountain en 1935, était chargé de veiller au bon déroulement des exécutions capitales. Parmi les prisonniers se trouvait un colosse du nom de John Coffe", "https://fr.web.img2.acsta.net/c_310_420/medias/nmedia/18/66/15/78/19254683.jpg", 5), 

(NULL, "La Liste de Schindler", "Evocation des années de guerre d'Oskar Schindler, industriel autrichien rentré à Cracovie en 1939 avec les troupes allemandes. Il va, tout au long de la guerre, protéger des juifs en les faisant travailler dans sa fabrique. ", "https://fr.web.img4.acsta.net/c_310_420/pictures/19/03/14/10/37/5927961.jpg", 2);

INSERT INTO season (id, number, year, description, program_id) VALUES
(NULL, 1, 2010, "La population entière a été ravagée par une épidémie d'origine inconnue, qui est envahie par les morts-vivants. ",1 ),
(NULL, 2, 2011, "Le groupe de survivants mené par Rick Grimes tente de survivre dans un monde envahi par les rôdeurs.",1 ),
(NULL, 3, 2012, "Après l'attaque de la ferme des Green par les morts-vivants, le groupe de Rick Grimes trouve refuge dans une prison infestée par les rôdeurs.",1 ),
(NULL, 4, 2013, "Le Gouverneur, en cavale après les événements de la saison précédente, rejoint un autre groupe et se prépare à attaquer la prison à nouveau.",1 ),
(NULL, 5, 2014, "Après l'enfermement du groupe de Rick dans le wagon A au Terminus.",1 );


INSERT INTO episode (id, title, number, synopsis, season_id) VALUES
(NULL, "Passé décomposé", 1, "Rick Grimes, shérif, est blessé à la suite d'une course-poursuite. Il se retrouve dans le coma. Cependant, lorsqu'il se réveille dans l'hôpital, il ne découvre que désolation et cadavres. Se rendant vite compte qu'il est seul, il décide d'essayer de retrouver sa femme Lori et son fils Carl. Lorsqu'il arrive chez lui, il s'aperçoit que sa maison est vide et que sa famille a disparu. Puis en ressortant de chez lui, il reçoit un coup sur la tête et tombe inconscient. Rick a en fait été assommé par Duane, le fils de Morgan, un médecin qui l'avait pris pour un zombie . Rick est désorienté lorsque Morgan lui apprend que l'humanité a été décimée par un phénomène étrange qui transforme les humains en errants. Il apprend comment le père et son fils font pour survivre (éviter la lumière et le bruit qui attirent les zombies). Le lendemain, Rick accompagne Morgan et Duane au commissariat pour leur donner des armes afin de se défendre, en prendre pour lui, et les munir, lui et Morgan, de talkie-walkie dans le but de rester en contact. Rick décide de partir pour Atlanta où il est persuadé que son fils et sa femme sont, car Morgan a entendu une rumeur selon laquelle il y aurait un camp de réfugiés. Les trois survivants promettent de se retrouver plus tard. Lorsque Rick se dirige vers la ville, il découvre que les rues sont jonchées de cadavres, mais aussi remplies de rôdeurs. Rick est dépassé, il laisse tomber son sac d'armes au milieu de la rue, et se réfugie dans un tank. C'est alors qu'une voix retentit dans la radio du char.",1),
(NULL, "Tripes", 2, "Rick parvient à s'échapper du tank grâce à l'aide de Glenn, dont il avait entendu la voix à la radio. Rick et Glenn se réunissent avec les compagnons de Glenn, un autre groupe de survivants dont Andrea, T-dog, Merle, Morales, Jacqui, venus pour se ravitailler au supermarché. Cependant, l'arrivée mouvementée de Rick les met tous en péril, l'attention des zombies ayant été attirée sur leur cachette. Assiégé par les zombies, le groupe parvient brièvement à communiquer par radio avec le groupe de Shane et Lori, mais ceux-ci décident qu'ils ne peuvent les aider, la présence de Rick ne leur ayant pas encore été communiquée. Dans le petit groupe cloîtré à l'intérieur du supermarché, les tensions s'exacerbent, particulièrement entre T-Dog, un noir et Merle Dixon, un blanc raciste, ce qui conduit Rick à intervenir en menottant Merle à un tuyau sur le toit du magasin. Rick, Andréa et Glenn planifient leur évasion du magasin toujours assiégé, l'idée est de se couvrir des lambeaux de chair et des boyaux des cadavres pour masquer leur odeur trop reconnaissable afin de pouvoir circuler parmi les zombies et atteindre des camions. Malgré la pluie qui a failli contrarier ce plan, le groupe parvient à s'échapper, dans un fourgon Dodge pour Andrea, Jacquie, T-Dog, Morales et Rick et une voiture pour Glenn. Seul Merle manque à l'appel après que T-Dog a accidentellement perdu la clé dans une canalisation, laissant Merle attaché au tuyau. Seule précaution : la porte d'accès au toit a été cadenassée pour préserver autant que possible Merle des rôdeurs…",1),
(NULL, "T’as qu’à discuter avec les grenouilles", 3, "De retour au camp avec le groupe de survivants du supermarché, Rick retrouve enfin et avec beaucoup d'émotion sa femme Lori et son fils Carl. Andrea quant à elle, rejoint sa jeune sœur Amy. Mais très vite, malgré l'intrusion d'un zombie près du camp, Rick décide, contre l'avis de Shane, de retourner à Atlanta chercher Merle Dixon ainsi que son sac d'armes abandonné en route et récupérer au passage le talkie-walkie laissé dans le sac et ainsi prévenir Morgan de ne pas se rendre dans le piège d'Atlanta. Il est accompagné de Daryl Dixon, le frère de Merle, plus jeune mais tout aussi violent, ainsi que Glenn qui connaît bien les lieux et T-Dog qui se sent redevable et Andrea. Lori prévient Shane de rester à distance de sa famille maintenant que Rick est de retour, car Shane lui avait dit que Rick était mort à l'hôpital. Les tensions s'exacerbent au camp entre une femme, Carole et son mari violent, Ed. Amy intervient pour prendre la défense de Carole avant qu'une bagarre éclate, au cours de laquelle Shane donne libre cours à sa colère. Il frappe Ed jusqu'à presque le tuer, ce qui effraie plusieurs témoins de la scène. L'équipe de rescousse parvient à Atlanta mais une fois arrivée sur le toit, elle découvre que Merle a utilisé une scie pour se couper la main et se libérer des menottes. Il a visiblement perdu beaucoup de sang mais reste introuvable…",1);

UPDATE season SET description = "La première saison de The Walking Dead, série télévisée américaine inspirée de la bande dessinée du même nom de Robert Kirkman et Charlie Adlard est constituée de six épisodes, diffusés du 31 octobre 2010 au 5 décembre 2010 sur AMC. "
WHERE number=1;
UPDATE season SET description = "La deuxième saison de The Walking Dead, série télévisée américaine inspirée de la bande dessinée du même nom de Robert Kirkman et Charlie Adlard est constituée de treize épisodes, diffusés du 16 octobre 2011 au 18 mars 2012 sur AMC. "
WHERE number=2;
UPDATE season SET description = "La troisième saison de The Walking Dead, série télévisée américaine inspirée de la bande dessinée du même nom de Robert Kirkman et Charlie Adlard est constituée de seize épisodes, diffusés du 14 octobre 2012 au 31 mars 2013 sur AMC."
WHERE number=3;
UPDATE season SET description = "La quatrième saison de The Walking Dead, série télévisée américaine inspirée de la bande dessinée du même nom de Robert Kirkman et Charlie Adlard est constituée de seize épisodes, diffusés du 13 octobre 2013 au 30 mars 2014 sur AMC. "
WHERE number=4;
UPDATE season SET description = "La cinquième saison de The Walking Dead, série télévisée américaine inspirée de la bande dessinée du même nom de Robert Kirkman et Charlie Adlard est constituée de seize épisodes, diffusés du 12 octobre 2014 au 29 mars 2015 sur AMC."
WHERE number=5;
